### ISSUE TITLE
Do you host this app somewhere? 

### ISSUE THREAD

**Issue by mkrdip** [altryne/Ipad-Simulator#4]
Hey, 

Do you host your app somewhere in web? or You know any site using your app? 

Thanks for the awesome work, Cheers!

**Comment by altryne** [comment]
Yeah I host it here :
alexw.me/ipad2
dunno if anyone is using it, there was a turkish site but i don't remember
it's url :)

**Comment by mkrdip** [comment]
Thanks Buddy!
